# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.playBtn = QtWidgets.QPushButton(Form)
        self.playBtn.setGeometry(QtCore.QRect(20, 120, 113, 32))
        self.playBtn.setObjectName("playBtn")
        self.pauseBtn = QtWidgets.QPushButton(Form)
        self.pauseBtn.setGeometry(QtCore.QRect(150, 120, 113, 32))
        self.pauseBtn.setObjectName("pauseBtn")
        self.stopBtn = QtWidgets.QPushButton(Form)
        self.stopBtn.setGeometry(QtCore.QRect(270, 120, 113, 32))
        self.stopBtn.setObjectName("stopBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.playBtn.setText(_translate("Form", "PushButton"))
        self.pauseBtn.setText(_translate("Form", "PushButton"))
        self.stopBtn.setText(_translate("Form", "PushButton"))
